import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Link
          href="/products
        "
        >
          Home
        </Link>

        <div>{children}</div>
      </body>
    </html>
  );
}
