import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
};

const navigations = [
  {
    title: "ABout",
    href: "/about",
  },
  {
    title: "Products",
    href: "/products",
  },
  {
    title: "Blog",
    href: "/blog",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-16">
          {navigations.map((navigate) => (
            <Link key={navigate.title} href={navigate.href}>
              <span>{navigate.title}</span>{" "}
              {/* Wrap text in a span so gap applies */}
            </Link>
          ))}
        </div>

        <div>{children}</div>
      </body>
    </html>
  );
}
